export const USER_LOADED = "USER_LOADED";
export const USER_AVATAR_LOADED = "USER_AVATAR_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";

export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const REGISTER_ACTIVATED = "REGISTER_ACTIVATED";

export const RESET_USER_PASSWORD = "RESET_USER_PASSWORD";
export const RESET_USER_PASSWORD_ERROR = "RESET_USER_PASSWORD_ERROR";

export const GET_USERS = "GET_USERS";
export const GET_USERS_ERROR = "GET_USERS_ERROR";

export const GET_CURRENT_USER_AVATAR = "GET_CURRENT_USER_AVATAR";
export const GET_CURRENT_USER_AVATAR_ERROR = "GET_CURRENT_USER_AVATAR_ERROR";

export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const GET_CURRENT_USER_ERROR = "GET_CURRENT_USER_ERROR";

export const USER_UPDATED = "USER_UPDATED";
export const USER_UPDATE_FAIL = "USER_UPDATE_FAIL";

export const GET_MATCHES = "GET_MATCHES";
export const MATCHES_LOADED = "MATCHES_LOADED";
export const MATCHES_FAIL = "MATCHES_FAIL";

export const GET_CONVERSATIONS = "GET_CONVERSATIONS";
export const GET_CONVERSATIONS_FAIL = "GET_CONVERSATIONS_FAIL";

export const GET_LIKED = "GET_LIKED";
export const GET_LIKED_FAIL = "GET_LIKED_FAIL";

export const LIKE_SUCCESS = "LIKE_SUCCESS";
export const LIKE_FAIL = "LIKE_FAIL";

export const UNLIKE_SUCCESS = "UNLIKE_SUCCESS";
export const UNLIKE_FAIL = "UNLIKE_FAIL";